name: Linters and coding standards checks

on:
  push:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
          sudo apt-add-repository 'deb https://repos.codelite.org/wx3.1.5/ubuntu/ focal universe'
          sudo apt-get update
          sudo apt-get install -y automake autoconf clang-tidy
          sudo apt-get install -y libwxbase3.1-0-unofficial \
                libwxbase3.1unofficial-dev \
                libwxgtk3.1-0-unofficial \
                libwxgtk3.1unofficial-dev \
                wx3.1-headers \
                wx-common
      - run: aclocal
      - run: automake --add-missing
      - run: autoconf
      - run: ./configure
      - run: make clang-tidy

