name: pygambit Python extension

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython nose2
          sudo apt-get install libxml2-dev libxslt-dev
      - name: Build extension
        run: |
          cd src
          python setup.py build
          python setup.py install
      - name: Run nosetests
        run: |
          cd src/pygambit/tests
          nose2
